### ISSUE TITLE
Debian packaging todo

### ISSUE THREAD

**Issue by dlech** [rhempel/ev3dev-lang-python#49]
- [x] Add `debian/copyright`
- [x] Fix missing comma in `setup.py`
- [x] Add extended description to `debian/control`
- [x] Standards version should be `3.9.5` in `debian/control`
- [ ] Remove `RELEASE-VERSION` from git and fix build

**Comment by rhempel** [comment]
I'm glad you know - really know - Debian packaging!

**Comment by dlech** [comment]
Also, `RELEASE-VERSION` is in `.gitignore`, so I am guessing that it is not supposed to be in git and there is something else wrong with the build.

**Comment by rhempel** [comment]
No, it's the fallback for git-version() ... I think

**Comment by ddemidov** [comment]
RELEASE-VERSION is created by setup.py when the package is built and is used on user side during installation. There is no need to put it under version control.

**Comment by rhempel** [comment]
Except the Debian package build method that @dlech uses needs to run git-version() and RELEASE-VERSION is the fallback - this is the disconnect between building a package for pypi and Debian - yes we can use the python-stdeb package to build a Debian package, but I think @dlech likes all packages built the same way....

**Comment by ddemidov** [comment]
One way to solve this is to run `python setup.py sdist`. This will create `RELEASE-VERSION`. But may be @dlech has better idea. I would not want to keep RELEASE-VERSION up-to-date manually.

**Comment by rhempel** [comment]
I don't - I still run the `python-stdeb` tools and merge in the resulting changes - hopefully not too many more releases.

**Comment by ddemidov** [comment]
Then we can just remove git_version.py, RELEASE-VERSION, and track the version manually in setup.py. But I feel I failed as a programmer when manual labor is involved in what I do :).

**Comment by rhempel** [comment]
Me too - let's leave git_version and RELEASE-VERSION for now, they are still helpful for other use cases

**Comment by rhempel** [comment]
I'll add notes in the README for the next version on how to do a release so that @dlech can build `python-ev3dev` and put it in the `ev3dev` Debian repository - first we need a working release build

**Comment by dlech** [comment]
We could create `RELEASE-VERSION` from the debian package version during the debian package build.

**Comment by rhempel** [comment]
Well, let's start by seeing if the current version (with RELEASE-VERSION) builds as a package in @dlech's environment and then figure out next steps. I have a few pull requests to merge in before we do an 0.5.0 release.

**Comment by dlech** [comment]
current git master builds with no errors or warning :+1:

**Comment by rhempel** [comment]
Yay! Thanks for testing this out @dlech. I'm going to close this now.
